In [1]:
import pandas as pd

In [2]:
# read data
diabetes = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv')

In [3]:
# display first 5 rows
diabetes.head()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
# display columns
diabetes.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [5]:
# define target (y)
y = diabetes['diabetes']

In [6]:
# define features (X)
X = diabetes.drop(['diabetes'], axis=1)

In [7]:
X = diabetes[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

In [9]:
# import train test split function
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

In [10]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((537, 8), (231, 8), (537,), (231,))

In [11]:
X_train

     pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
377            1       87         60       37       75  37.2  0.509   22
393            4      116         72       12       87  22.1  0.463   37
662            8      167        106       46      231  37.6  0.165   43
367            0      101         64       17        0  21.0  0.252   21
233            4      122         68        0        0  35.0  0.394   29
..           ...      ...        ...      ...      ...   ...    ...  ...
689            1      144         82       46      180  46.1  0.335   46
730            3      130         78       23       79  28.4  0.323   34
464           10      115         98        0        0  24.0  1.022   34
223            7      142         60       33      190  28.8  0.687   61
485            0      135         68       42      250  42.3  0.365   24

[537 rows x 8 columns]